replicaCount: 3

image:
  repository: cybersecmas/harness-tutorial-cyberdevops
  tag: <+pipeline.sequenceId>
  pullPolicy: IfNotPresent

service:
  enabled: true
  name: custom-nginx-service
  type: LoadBalancer
  port: 80
  targetPort: 80

resources: {}
